vocab:
  pad_token: "<pad>"
  bos_token: "<bos>"
  eos_token: "<eos>"
  unk_token: "<unk>"
  annotation_paths: 
    - data/UIT_HWDB_line/train.json
    - data/UIT_HWDB_line/test.json

dataset:
  train:
    annotation_path: data/UIT_HWDB_line/train.json
    feature_path: data/UIT_HWDB_line/features/train
  test:
    annotation_path: data/UIT_HWDB_line/test.json
    feature_path: data/UIT_HWDB_line/features/test

training:
  checkpoint_path: checkpoints
  batch_size: 64
  lr: 0.01
  warmup: 2000
  patient: 10
  score: WER

model:
  d_model: 256
  d_feat: 2048
  n_layers: 3
  n_head: 8
  dim_ffw: 2048
  dropout: 0.1
  device: cuda
  max_len: 4096
